### ISSUE TITLE
Handle trajectory unrecognized by FAHClient

### ISSUE THREAD

**Issue by Jesse-V** [Jesse-V/Folding-Atomata#13]
Currently, FAHClient cannot read FahCore 17 WU trajectory files. This results in the "trajectory" command returning a blank PyON array. Here's an example from EXT64: http://pastebin.com/X2NgRGJm This case should be handled gracefully.

**Comment by proteneer** [comment]
@jcoffland Joseph, any ideas?

**Comment by Jesse-V** [comment]
@proteneer, I was just going to start from what you said: "System XML files contains masses of each atom, which can then be mapped to atom types. Positions, velocities and forces are all contained in the xtc file. The format can be found and read using xdrlib (a simple google suffices to obtain this info) You should note that we use periodic images, so you have to adjust the positions by putting it in the periodic box. I believe the size of the periodic box is contained in the state.xml files as well as the xtc file."

https://fah-web.stanford.edu/projects/FAHClient/ticket/980 is the ticket for FAHClient/FAHViewer.

**Comment by proteneer** [comment]
OK, bond information can be a bit tricky. Look for harmonic bond forces in the system.xml file if you want to figure out the connectivity.

**Comment by jcoffland** [comment]
FAHClient will read core 0x17 trajectory files in the next release.

**Comment by Jesse-V** [comment]
Cool, thanks. I'll just wait for that then. :)
