### ISSUE TITLE
Ensure that PPA and .deb builds work correctly

### ISSUE THREAD

**Issue by Jesse-V** [Jesse-V/Folding-Atomata#15]
I'd like to distribute this project via a Launchpad PPA, a .deb package, and as an install-from-source. Before continuing towards a final release, I need to ensure that my PPA and .deb installers and builds work correctly and run as intended on other Linux machines.

**Comment by Jesse-V** [comment]
Builds should be for Debian (wheezy and unstable) and for Ubuntu (Precise, Quantal, Raring), with i386 and amd64 arches of course.

**Comment by Jesse-V** [comment]
Launchpad only supports Ubuntu, so Debian users have to use the .deb file. *buntu/Mint users can use the PPA.

I should be able to build for Quantal, and then use Launchpad's "Copy Package" feature to copy the package into the precise/raring universes.

**Comment by Jesse-V** [comment]
The .deb file produced from Launchpad installs and uninstalls correctly. It can be launched by typing "FoldingAtomata" in the Terminal.

**Comment by Jesse-V** [comment]
The package can be updated via the Update Manager, and looks good in Synaptic Package Manager.

**Comment by proteneer** [comment]
nice!

**Comment by Jesse-V** [comment]
Apparently, Jim Erickson is beta testing 13.10 (Saucy). I need to offer a build for that too in the PPA.
Looks like the PPA and .deb files are working correctly though. :)
