### ISSUE TITLE
Update gitInstall script to reflect png++

### ISSUE THREAD

**Issue by Jesse-V** [Jesse-V/Folding-Atomata#34]
The gitInstall script does not install libpng++, which will be needed by #3.

It should also be renamed to "installFromSource.sh" to avoid the implication that it's installing git itself.

Thanks to TheFlipside for helping me realize this.

**Comment by proteneer** [comment]
I think it's a bit confusing to automatically invoke apt-get when executing the installFromSrc.sh. Maybe call it something like "downloadLibraries" and separate out the apt-get part? It's generally understood that linux users know how to get their packages. Also, non deb based distros don't use apt-get.

**Comment by Jesse-V** [comment]
Good idea. I was planning on only supporting Debian/Ubuntu/Mint, but TheFlipside runs Linux From Scratch and he got everything to run just fine by compiling and installing everything manually. Once the libraries are installed, the choice of distro shouldn't really matter. Technically, one could install the packages in Fedora and then run it there just fine (haven't tested this though) but that would use yum instead of apt-get. Either way, you're right, I should separate that out.

< Jesse_V > so what can I do to make that easier, besides defining that variable and checking for png++?
< TheFlipside > well hard to say, when people do it they also have to fix that outdated png++
< TheFlipside > thats not even in the LFS book
< TheFlipside > apart from that its pretty straightforward, people just have to do this "cd src && cmake . && make" and as root "make install"
< Jesse_V > ah ok
< TheFlipside > thats very simple basics for everyone who does BLFS

**Comment by proteneer** [comment]
I'd recommend just set up some FINDxxxx cmake file modules:

http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries#Writing_find_modules

PS - its generally safe to assume that developers can setup the libs in whatever distro they work with.

**Comment by Jesse-V** [comment]
Ok, I just wanted to make the install-from-source option as close to easy as the .deb or PPA install. That was my goal, but if I'm supporting more than Debian/Ubuntu/Mint, the libraries need to be handled a bit more gracefully. Thanks very much for the link to the CMake docs. :)

**Comment by proteneer** [comment]
PPS - what we do in OpenMM is to include the source files for the libraries and build them using our own cmake modules directly. This way, we completely alleviate the user of the library from the headaches associated with dependency hell (wrong library version, bugs in specific weird libraries, libraries not built with multithreading or zlib compression(_cough boost_iostreams/cbang i'm looking at you_), etc.) If the libraries aren't big/tough-to-build I'd recommend it 

This is a bit hardcore.

**Comment by Jesse-V** [comment]
> This is a bit hardcore.

Really? You don't say... :)

The dependencies here are pretty small and limited though: glew, freeglut, and png++ are the main ones.
