### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by proteneer** [Jesse-V/Folding-Atomata#38]
I highly recommend you putting together a license for this soon. Generally developers are weary of touching code that doesn't have a license for various legal reasons. Consider LGPL, MIT/BSD, or ugh, even GPL?

**Comment by Jesse-V** [comment]
A license is already in place. Check all the source files and in /debian. I confess, I uhh, I used GPLv3+.
FAHViewer is under GPLv2+. I reviewed the GPLv2 vs GPLv3 debate, and thought that GPLv3 was a more modern option. The choice of license did seem a bit controversial, and it got very technical very fast. I did double-check that the libraries I use are compatible with my choice of license.

I was looking at http://choosealicense.com/ and http://choosealicense.com/licenses/
I'm happy to reconsider. What would be your recommendation and why?

**Comment by proteneer** [comment]
Usually the copyright in /debian/ is different from a LICENSE, and it's customary to put the license in the root folder of your project. 

GPLv2/v3 isn't really the big debate, as the differences are minor IMO. I think GPL is fine for now as well.

**Comment by Jesse-V** [comment]
Good idea, I forgot about that Debian recommendation.

The choice of license would need to be finalized before I expose this program more publically. I think I'll stick with GPLv3, but it's my understanding that I can change licenses if I so choose.
