### ISSUE TITLE
Display proteins from all slots

### ISSUE THREAD

**Issue by Jesse-V** [Jesse-V/Folding-Atomata#9]
The user should be able to look at the proteins from all the running slots at the same time. This makes it more obvious how much work is being done at the same time. The proteins should be spaced out accordingly so as to be conflicting with one another.

**Comment by Jesse-V** [comment]
This would need to be completed after #44, for performance reasons. One of the potential problems with showing all the proteins is that the FPS may be drastically affected, so it's important to get the rendering as efficient as possible beforehand.

**Comment by Jesse-V** [comment]
This is much more doable now, but I think it might be a good idea if this was optional. The question is whether it should be on by default, or off by default.

**Comment by proteneer** [comment]
got a screenshot?

**Comment by Jesse-V** [comment]
Of the 100k atoms I was rendering? There's not much to look at, it was a test render. Just use a for-loop to make 2D square grid of N atoms, and then I just increased N to see what happened. The visual net result was nothing more than a bunch of white spheres laid out on a grid, nothing fancy to look at there.

Nvidia GT 240m (pre-Fermi) under Linux with Nvidia drivers handled 100k atoms at 10 FPS. Seems promising. Jimerickson suggested that the feature described in this ticket be enabled by default, and I agree.

**Comment by Jesse-V** [comment]
But if you insist, here you go: 
![screenshot from 2013-10-07 21 48 03](https://f.cloud.github.com/assets/2314417/1286308/81065cea-2fcc-11e3-9cb5-9e0f07192cb6.png)
